name: Check version

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    container: zepben/pipeline-basic
    env:
      NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NEXUS_MAVEN_SNAPSHOT: ${{ secrets.NEXUS_MAVEN_SNAPSHOT }}
      NEXUS_MAVEN_RELEASE: ${{ secrets.NEXUS_MAVEN_RELEASE }}
    steps:
      - uses: actions/checkout@v4

      - name: Work around git permission issue
        run: |
          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
          git config --global --add safe.directory /__w/$dname/$dname
        shell: sh

      - name: Check version doesn't already exist
        run: |
          /scripts/release-checks.sh --java --maven pom.xml
        shell: bash

