name: Release

on:
  repository_dispatch:
    types: [trigger-release]
  workflow_dispatch:


jobs:
  deploy-central:
    runs-on: ubuntu-latest
    container: zepben/pipeline-java-ewb
    env:
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
    steps:
      - uses: actions/checkout@v4

      - name: Maven deploy to Central
        id: build
        uses: zepben/maven-deploy-central-action@main
        with:
          ZEPBEN_GPG_KEY: ${{ secrets.ZEPBEN_GPG_KEY_B64 }}
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
          SETTINGS_PATH: "for-ci-build-image/maven-settings.xml"
          NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_RELEASE_URL: ${{ secrets.NEXUS_MAVEN_RELEASE }}
          NEXUS_SNAPSHOT_URL: ${{ secrets.NEXUS_MAVEN_SNAPSHOT }}
          PROFILE: ossrh
        continue-on-error: false

      - name: Trigger container build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          event-type: build-container
          client-payload: '{ "push_image": "true", "version": "${{ github.event.client_payload.version }}" }'
